### ISSUE TITLE
RemoveDuplicates destroys pods even if every node has a running instance

### ISSUE THREAD

**Issue by darren-mcdonald** [kubernetes-sigs/descheduler#1040]
**What version of descheduler are you using?**

descheduler version: 0.23.2

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**
1.21.7

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
We have a deployment with a HPA. It has scaled the deployment to 6 pods. The nodepool has 4 nodes in it. The RemoveDuplicates policy is seeing that 2 pods are duplicates and is constantly destroying them and re-provisioning

**What did you expect to see?**
Descheduler to notice that all nodes have at least 1 pod instance of the deployment and therefore any extras marked as duplicates are fine.

**What did you see instead?**
Constantly destroying a number of pods that are equal to the replica set - number of nodes. E.g 6 pods - 4 nodes = 2 duplicates

**Comment by damemi** [comment]
There have been other reports similar to this (for context https://github.com/kubernetes-sigs/descheduler/issues/263, https://github.com/kubernetes-sigs/descheduler/issues/921)

#921 sounds like your situation. In that case, I recommended trying pod topology constraints to spread your pods, rather than relying on RemoveDuplicates. Would that work for you?

**Comment by darren-mcdonald** [comment]
It sounds like it would partially work but only in the case whether RemoveDuplicates is disabled.

Lets take a scenario where I have 5 pods running across 5 nodes and the cluster has autoscaling on. Later in the day it scales down to 3 nodes. Topology spread constraints can help me there (and I believe there are [default constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints) in kube 1.24) by spreading the extra pods evenly across the remaining nodes.

If I have RemoveDuplicates enabled here then those extra 2 pods keep getting destroyed and recreated over and over.

Now lets say I disable RemoveDuplicates. When my cluster scales up again to 5 nodes, wont those pods remain where they are rather than Descheduler identifying that it can spread them to the new nodes?

It feels like you were on to the solution here in this [comment](https://github.com/kubernetes-sigs/descheduler/pull/463#pullrequestreview-548380787). You take the number of pods and divide by the number of nodes to get the average and then if a node has more pods than ceiling(average) then shift some pods off that node. Another strategy might be to just check if all nodes that pass nodeaffinity have at least 1 instance of the pod on them, if true then don't run RemoveDuplicates. It's not as neat and might not evenly spread but in my mind if duplicates are inevitable due to having more pods than nodes and all nodes currently have an instance then the rule shouldn't run.

What are your thoughts?

**Comment by damemi** [comment]
> Now lets say I disable RemoveDuplicates. When my cluster scales up again to 5 nodes, wont those pods remain where they are rather than Descheduler identifying that it can spread them to the new nodes?

Descheduler has the [RemovePodsViolatingTopologySpreadConstraint](https://github.com/kubernetes-sigs/descheduler#removepodsviolatingtopologyspreadconstraint) strategy for this. I think using spreading constraints + the topology spread descheduler strategy is the solution you want.

RemoveDuplicates was an early attempt at solving this kind of problem before topology spreading constraints existed in k8s. Since then, topology spreading has replaced the need for RemoveDuplicates in most cases as a better option.

For the comment you linked, I thought that *was* the solution we merged, so maybe there is a bug in that logic. Given what I said above though, we may just want to think about deprecating RemoveDuplicates in favor of topology spread constraints. @ingvagabund wdyt about that?

**Comment by ingvagabund** [comment]
The difference between those strategies is in a definition of what is a duplicate. The RemoveDuplicates  strategy constructs a duplicate based on `pod.Namespace/owner.Kind/owner.Name/image`. In theory you could have e.g. two or more identical ReplicaSets in the same namespace owned by the same owner. Just with a different RS name and their corresponding matching labels. The RemoveDuplicates strategy will treat all pods matched by all these RSs as a single pool of duplicated pods. One can see it as e.g. three buckets of marbles getting evenly spread among nodes. One node can have 1/3 of marbles of the first bucket, other node 2/3 of marbles of the first bucket. Other nodes getting the rest of the marbles from the remaining buckets.

I wonder whether one can achieve the same behavior through RemovePodsViolatingTopologySpreadConstraint strategy. Probably through setting `labelSelector` in the spec. Unless there's a obvious inconsistency in the behavior of both strategies RemoveDuplicates got superseded by RemovePodsViolatingTopologySpreadConstraint. Better to properly check but +1 for the deprecation.

**Comment by darren-mcdonald** [comment]
In that case I'll take a look at using the spreading constraints + the topology spread descheduler strategy. Would you happen to know if I need to create my own spread constraints or if descheduler would act on the kube 1.24+ [default constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints)?

**Comment by damemi** [comment]
@darren-mcdonald I think that's come up as a suggestion before but we haven't implemented it. It should be possible for us to add though

@ingvagabund good point on the different definitions of duplicates. In that case maybe we keep it around, but a note on it that recommends PodTopologySpread would be informative for people since it's a common confusion.
