### ISSUE TITLE
Why does Label filtering not support all strategies？

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes-sigs/descheduler#1118]
Why does Label filtering not support all strategies？

**Comment by damemi** [comment]
@ingvagabund or @knelasevero can correct me if I'm wrong, but labelSelector will be available for all strategies in the next v1alpha2 release now that it's an option on the [DefaultEvictor](https://github.com/kubernetes-sigs/descheduler#evictor-plugin-configuration-default-evictor).

For historical context, label filtering was previously implemented as part of the pod-listing phase, which would make strategies like LowNodeUtilization less accurate because these strategies fundamentally need to know the state of the entire node to be effective. And the more pods you exclude from this, the less it makes sense to even run those strategies at all.

As an Evictor option, it allows these strategies to be aware of all pods on the node but filter out which ones are eligible for eviction. This can still hurt the overall effectiveness of the strategy if abused, but it is much clearer to the user when that's happening because we can log pods that are skipped during the eviction phase (vs logging which pods are not even considered during the pod-listing phase).

**Comment by AllenZMC** [comment]
@damemi  `DefaultEvictor` Label filtering has no effect.

**Comment by ingvagabund** [comment]
We will be updating the documentation once the v1alpha2 API is officially out. Even though the current implementation already allows use of v1alpha2, the final shape can still get adjusted.

**Comment by engineerbharath12** [comment]
@damemi I would like to confirm if the current label filtering mechanism applies to all strategies, specifically the "lowNodeUtilization" strategy. Also, could you please clarify if this label filtering occurs during the pod listing or pod eviction phase? It would be ideal if this feature could be applied during the pod eviction phase. Considering the overall node utilization, this would enable us to evict pods from nodes based on their labels.

**Comment by ingvagabund** [comment]
> could you please clarify if this label filtering occurs during the pod listing or pod eviction phase?

https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/nodeutilization/nodeutilization.go#L259

The label filtering is applicable for pod eviction. Any pod that does not comply to the label selector is considered as non removable.

**Comment by a7i** [comment]
`labelSelector` is now part of DefaultEvictor in `v1alpha2`

/close
