### ISSUE TITLE
Poor defaults in Helm chart

### ISSUE THREAD

**Issue by jgillich** [kubernetes-sigs/descheduler#1266]
Some of the defaults in the Helm charts seem rather poor:

* A lot of strategies are enabled by default. IMO they should be opt-in rather than opt-out; with the way values are usually merged, you'd have to manually disable 7 strategies to start from scratch
* 500m cpu request, which applies to both the cron job and the deployment. For the first one it seems unnecessary, whereas it's plain wasteful for the latter one. I'd suggest tuning it down to 100m
* The default schedule is every other minute (or every 5 minutes for deployment). Is that necessary? This could create a lot of load on the API and the nodes, wouldn't every 30-60 minutes be good enough for a default?

Thoughts?

**Comment by a7i** [comment]
Hi @jgillich thanks for the feedback! Please find my response below:

>A lot of strategies are enabled by default.

This goes way once we move to v1alpha2 in this PR: https://github.com/kubernetes-sigs/descheduler/pull/1139/files
That's because `profiles` is an array

>500m cpu request

Yes, I agree. In a cluster of 10k pods, it uses around 100m. Would you be open to creating a PR for this?

>The default schedule is every other minute (or every 5 minutes for deployment). Is that necessary? 

It depends, we run Descheduler every 2 mins to meet our SLOs. I think this is a good default. 30-60 minutes would burn our SLO budgets in a single day and that's not really a good default for my use-case.

**Comment by ryanovas** [comment]
Is this issue closed on purpose? It seems like these defaults are still active and trying to deploy this with defaults into a smaller cluster can't even schedule the pod
