### ISSUE TITLE
Consider implementing pod (anti)affinity checks in NodeFit 

### ISSUE THREAD

**Issue by logyball** [kubernetes-sigs/descheduler#1279]
**Is your feature request related to a problem? Please describe.**
 Hello, we have been running into a situation which was somewhat surprising until I [dug into the code](https://github.com/kubernetes-sigs/descheduler/blob/a01322a5e5a74b787912a1e70a5d48f7fea14275/pkg/descheduler/node/node.go#L105) and learned that `NodeFit` does not take into account _all_ scheduler predicates, notably pod (anti)Affinity.  At our organization, we've had multiple occasions where using descheduler `HighNodeUtilization` profile + GKE's `optimize-utilization` [autoscaling profile](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#autoscaling_profiles) has bit us _because_ we assumed that NodeFit and the kube-scheduler would agree.  

The basic situation is:

- Node A contains Pod X
- Node B contains Pod Y
- Pod X and Pod Y have a pod anti-affinity rule that prevents them from being scheduled on the same node
- Node A is considered "underutilized" by the descheduler
- Node B is _not_ considered "underutilized"
- NodeFit algorithm is run and determines that Pod X can schedule on Node B
- descheduler evicts Pod X
- kube-scheduler determines Pod X cannot schedule on Node B because of Pod X/Y's anti-affinity
- kube-scheduler schedules Pod X on Node A
- The cycle continues with each loop of the descheduler

**Describe the solution you'd like**
I suggest that we look into implementing Pod (anti)affinity checks into the NodeFit calculation, and would be happy to look into contributing it.  It probably adds a decent amount of complexity, but would likely make the descheduler's decisions more closely resemble that of the kube-scheduler, what do you think?

**Describe alternatives you've considered**
- Do nothing: perhaps call out in the documentation that the NodeFit arg does not take into account pod (anti)affinity

**What version of descheduler are you using?**

descheduler version: v0.27.x

**Comment by logyball** [comment]
Also, in a bit of follow up, after digging into a bit of how the scheduler implements these checks, it's not easy to parse for me.  I'd love some guidance here if this is an avenue we'd like to pursue.  It looks like in the past (last seen in v1.9.11 of k8s), there was a [Predicate checker](https://github.com/kubernetes/kubernetes/blob/v1.9.11/plugin/pkg/scheduler/scheduler.go) that we could probably have used to good effect.  However, now the ecosystem looks a bit more complex.

**Comment by gyuvaraj10** [comment]
We have also run this issue with the PodAntiAffinity in our case is a preferred choice. We have noticed that after the pod eviction the node still remained and the pod is scheduled onto the same node as the cluster autoscaler did not scale down the node immediately.

**Comment by nikimanoledaki** [comment]
@kubernetes/sig-scheduling-feature-request, hi! 👋 

I would be interested in picking up this issue and contributing a PR to add this feature.

In the scenario outlined above by @logyball, NodeFit() runs and determines Pod X can be scheduled on Node B _when it shouldn't_. The happy path would be that NodeFit() should run and determine that Pod X cannot be scheduled on Node B.

@a7i mentioned [here](https://github.com/kubernetes-sigs/descheduler/issues/1149#issuecomment-1785291246) that this could be implemented as a patch.

The solution would be to add a predicate to [NodeFit()](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/node/node.go#L107) so that is considers pod anti-affinity. Something like this:
```Go
func NodeFit(nodeIndexer podutil.GetPodsAssignedToNodeFunc, pod *v1.Pod, node *v1.Node) []error {

...
	// Check if pod matches pod anti-affinity rule(s) of other pod(s) on node
	if ok, err := utils.PodMatchesAntiAffinityRule(pod, node); err != nil { // add check in pkg/utils or below
		errors = append(errors, err)
	} else if !ok {
		errors = append(errors, fmt.Errorf("pod violates pod anti-affinity rule of other pod on the node"))
	}

	return errors
}
```

Optional: The strategy [RemovePodsViolatingInterPodAntiAffinity](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go) already contains logic for fetching and comparing the pod anti-affinity rule of pods, which could be refactored, moved to `pkg/utils`, and used for `NodeFit()` as well.

Happy to assign myself to this issue once I get the green light from SIG Scheduling/descheduler maintainers :)
