### ISSUE TITLE
Add a strategy for taints and tolerations

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes-sigs/descheduler#131]
Recently one of the users requested a strategy for taints and tolerations. While I don't have cycles to work on this, I would be more than happy to review if anyone in the community is interested to work on.

**Comment by paktek123** [comment]
any more details, please expand

**Comment by chadswen** [comment]
@paktek123 Take a look at this issue for a use case currently implemented with Draino that could be replaced by descheduler: https://github.com/kubernetes/node-problem-detector/issues/199#issue-354954628

**Comment by aveshagarwal** [comment]
> any more details, please expand, I would be interested in contributing

Lets say a pod was scheduled on a node where there is mismatch between pod's toleration and node's taints, and it could be due to that the pod was scheduled on a node whose taints were later updated. Since, pod's tolerations were only checked at the time admission, and later node's taints were updated, pod continued running on the node, so it only applies for NoSchedule taints.

In summary, it would work as follows:

1. get a list of nods (which already exists)
2. get a list of pods on each node (which already exists)
3. Verify that the node's taints (NoSchedule) are still satisfied by its pods' tolerations.
4. As per previous step, If not satisfied, evict the pod.
5. If yes (still satisfied), continue checking other pods until you have reached the end of list of pods for that node.
6. Repeat above for all nodes.

**Comment by paktek123** [comment]
Thanks for the explanation, I will hopefully try to contribute next week

**Comment by warmchang** [comment]
Nice idea! It is also very useful for customizing the migration time of POD.

**Comment by pravarag** [comment]
@seanmalloy @damemi looks like this issue hasn't been picked up in long time. Is it okay if I give it a try? will post my queries here if any.

/assign

**Comment by StevenACoffman** [comment]
Please do!

**Comment by pravarag** [comment]
@damemi @aveshagarwal one query around this description mentioned [here](https://github.com/kubernetes-sigs/descheduler/issues/131#issuecomment-474528862), Are we looking to add a new check in api itself like somewhere here: https://github.com/kubernetes-sigs/descheduler/tree/master/pkg/descheduler/node or this feature is going to be a new change w.r.t command line options as well maybe here: https://github.com/kubernetes-sigs/descheduler/tree/master/cmd/descheduler/app ?

**Comment by damemi** [comment]
I'm not actually sure why this issue is still open, I might have mistakenly reopened it when it went stale... we have a Taints/Tolerations strategy that was merged out of this issue (https://github.com/kubernetes-sigs/descheduler#removepodsviolatingnodetaints)

Is there something that strategy is missing from the discussion here? Or can we close this?

**Comment by StevenACoffman** [comment]
Just checking, but is it now possible to:

1. Detect permanent node problems and set Node Conditions using the Node Problem Detector and the scheduler's `TaintNodesByCondition` functionality.
2. Configure [Descheduler](https://github.com/kubernetes-incubator/descheduler) to deschedule pods based on taints to cordon and drain nodes when they exhibit the NPD's `KernelDeadlock` condition, or a variant of `KernelDeadlock` we call `VolumeTaskHung`.
3. Let the Cluster Autoscaler scale down underutilised nodes, including the nodes Descheduler has drained.

If so, is there an example?

**Comment by damemi** [comment]
@StevenACoffman yes, the descheduler will evict any pods that are currently running on a node that has any `NoSchedule` taint that the pods do not tolerate. So, your use case should work with the `RemovePodsViolatingNodeTaints` strategy

**Comment by pravarag** [comment]
Thanks @damemi for clarifying, I guess this issue will be closed now 🙂
