### ISSUE TITLE
Potentially create BalanceNodeUtilization strategy

### ISSUE THREAD

**Issue by lukemassa** [kubernetes-sigs/descheduler#184]
I've looked over the LowNodeUtilization strategy, and I'm not sure it fits my use case. I'm not sure if the right solution is to build a different strategy, but I wanted to spell it out to get your thoughts.

My understanding is LowNodeUtilization is trying to optimize for making the most use out of your cluster, there's no reason to run nodes if you aren't going to fill them up.

The issue I am trying to solve is that I know my cluster behaves badly when CPU and memory are near 100% (CPU because of some sort of contention, memory because if system OOM killer has to get involved it leaves things in a bad state). Because of that, I would like to optimize for *preventing any nodes from running too hot, as opposed to making sure that all nodes are being used*.

My thought was, instead of having thresholds and targets, to have some way of quantifying how "unbalanced" a cluster is, and have a toleration of that balance that is inevitable due to bin packing issues, and evict pods if they fall out of that range. (Something like how many standard deviations away from the mean a given node is, but probably with the language of binomial distributions since these are percentages.) As far as I can tell, this cannot be achieved with LowNodeUtilization, since I do not know a priori what levels my cluster is running at.

Please let me know if I'm way off base on this one, I've only just started playing with the descheduler. I was thinking of implementing something like the balancer I describe and came across this project, and if this seems like a good idea to you I'd love to try to implement this in the context of your app.

**Comment by lukemassa** [comment]
Hey @ravisantoshgudimetla; we spoke briefly about this at kubecon after the SIG-scheduler deep dive.

I wonder if a more holistic approach would be take each pod and run them through a copy of the scheduler, and see how "wrong" they are, then have some threshold after which an eviction would happen. For example, if a pod is currently on node X, but now node X has a much lower scheduling score than other nodes, evict the pod.

I'm afraid that any attempt to optimize for a specific thing (low/high node utilization, affinity, etc) has the risk of not taking the whole scheduling context into the picture, and could easily end up in pathological cases. For example, a node might be heavily utilized, but must be that way because of selectors/affinity, so continuing to evict from it would be useless.

I'm not sure if an approach like this would be possible, but if so, it could subsume the other strategies, and would get for free any improvements to the scheduler itself.

**Comment by alperbas** [comment]
Hey @ravisantoshgudimetla, instead of descheduler you could try to optimise eviction policies to prevent OOM kills.
`--system-reserved=memory=2Gi --eviction-soft=memory.available<5Gi --eviction-soft-grace-period=memory.available=5m` 
If you use the kubelet settings as above for example, it will trigger soft eviction and gracefully stop the the containers above the limit.
I'm not sure if it would help your case but you give it a try.

**Comment by ravisantoshgudimetla** [comment]
Sorry, I missed this. I think identifying the nodes that have better score for a given pod than the current node where the pod is running seems reasonable and is actually of the goals for descheduler. We're in the process of breaking `k8s.io/scheduler` dependencies and we think this strategy seems reasonable as @seanmalloy pointed out.

**Comment by Dentrax** [comment]
/remove-lifecycle rotten
/reopen

Hey there! We hit a use-case where the `nodeutilization` plugin could not do much.

I did carefully read the comments and IMHO this `BalanceNodeUtilization` plugin idea is really cool to _balance_ the _pods_ across _all nodes_. It would be good load balancing practice for the cluster. FWIW, I think we should prioritize this plugin idea and discuss further about. cc @damemi @ingvagabund @seanmalloy 

I'm not so sure about if `nodeutilization` and `balanceutilization` could mutually exclusive to run at same time. Please enlighten me here: Would be `balanceutilization` obsoletes the `nodeutilization` plugin? (Since nodes never go low/high utilization state since all will keep balanced by balanceutilization.)

As @lukemassa already mentioned:
> Something like how many standard deviations away from the mean a given node is, but probably with the language of binomial distributions since these are percentages.

We can use _standard deviation_ (with some margin of error (confidence interval)) to calculate drift/gap between lowest and highest pod counts accross _Ready, Schedulable_ nodes.

Eventually we get something like:

```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "BalanceNodeUtilization":
     enabled: true
     params:
       maxAllowedStandardDeviationPercent: 5%
```

We are (w/ @eminaktas) volunteer to implement this plugin once we get agreement on this proposal!

---

See the _Pods per Node_ metrics and our use-case below:

![Screen Shot 2022-11-02 at 15 04 09](https://user-images.githubusercontent.com/16493751/199485342-0bd45f43-316b-4fdb-990e-0a5de3b5927e.png)

Most of the nodes are `overutilized` or `appropriately utilized`. The plugin doesn't get triggered because of:

```
lownodeutilization.go:118] "Criteria for a node under utilization" CPU=30 Mem=30 Pods=30
lownodeutilization.go:119] "Number of underutilized nodes" totalNumber=0
lownodeutilization.go:132] "Criteria for a node above target utilization" CPU=70 Mem=70 Pods=70
lownodeutilization.go:133] "Number of overutilized nodes" totalNumber=12
lownodeutilization.go:136] "No node is underutilized, nothing to do here, you might tune your thresholds further"
```

---

The idea is to keep all pod counts as balanced as possible _per_ node! Eventually we expect ~45-50 pod counts per node. (as per the image above)

Waiting your thoughts!

**Comment by damemi** [comment]
I'm not sure I understand the difference between that and LowNodeUtilization. 30/70 are pretty wide thresholds for balancing utilization, so there will be variance in there. A closer threshold gap should trigger more evictions and ultimately lead to a more balanced state.

The other problem is that even if the descheduler calculates an optimal distribution, that doesn't mean those pods will get scheduled in that distribution. You would need a matching scheduler plugin to do that, and it would probably need to work in a batch scheduling format to consider all of the evicted pods at once.

But by default the scheduler does try to balance pods across nodes, prioritizing the lowest-utilized node. That's the idea behind LowNodeUtilization, bringing me back to my question that it's not clear to me how this differs. Maybe if you could provide an example it would help illustrate the idea?
