### ISSUE TITLE
RemoveDuplicates should average out based on node count

### ISSUE THREAD

**Issue by mattwilliamson** [kubernetes-sigs/descheduler#263]
When using `RemoveDuplicates`, if I have 5 nodes and a ReplicaSet of 10, 2 pods should be on each. descheduler instead continuously evicts half of them even though it will end up with the same distribution.

**Comment by palmerabollo** [comment]
Related https://github.com/kubernetes-sigs/descheduler/issues/252

**Comment by hanumanthan** [comment]
hi @seanmalloy Is this bug as new contributor I can work on ?
If yes, can you please let me know what needs to be done here and point me to the method/file to be fixed. Happy to take a stab on this issue.

**Comment by seanmalloy** [comment]
@hanumanthan here are the files that would need to be changed to fix this bug.

The code is in file `pkg/descheduler/strategies/duplicates.go`. The unit tests are in file `pkg/descheduler/strategies/duplicates_test.go`. The documentation is here, https://github.com/kubernetes-sigs/descheduler#removeduplicates.

After reviewing the code in `pkg/descheduler/strategies/duplicates.go` I believe that this bug can be worked on by a new contributor. Let me know if you have any questions or if you feel like this bug is not appropriate for a new contributor. I can help with finding another good first issue for you to work on.

Thanks for your help!

cc: @damemi @ingvagabund

**Comment by hanumanthan** [comment]
Hi, Is this approach correct?

After getting the pods list on a node, we get the replicaset for each pod. 
If the `spec.replicas` count is greater than the total nodes available, we ignore the pod for eviction.

**Scenarios**
- 2 nodes, 3 replicas --> One node will have 2 pods and other will have one. `spec.replicas` > nodes count, so no pod will be evicted
- 4 nodes, 2 replicas --> assuming both pods are on node 1. `spec.replicas` < nodes count. Proceed with further logic for duplicates

The drawback in this approach is the rs will be queried for each pod which will result in duplicate api calls. We can create a map that holds the rs with the pods uid as the key. Query the map using  pod `ownerReferences.uid` and if RS is not found, invoke the api

**Comment by ingvagabund** [comment]
Hello @hanumanthan, thanks for refreshing the topic. There are already some approaches on the way. Namely:

- @safanaj https://github.com/kubernetes-sigs/descheduler/pull/269
- @mattwilliamson https://github.com/mattwilliamson/descheduler/commit/1fc84f5c2a6961a6f9186f78d15a0b275e87a598

Can you sync with @safanaj and @mattwilliamson ? Sounds like you have similar approaches.

**Comment by damemi** [comment]
We haven't heard back from @safanaj since trying to get an update a couple weeks ago (https://github.com/kubernetes-sigs/descheduler/pull/269#issuecomment-635373663), so I won't block anyone from taking up a new PR at this point @mattwilliamson @hanumanthan

**Comment by hanumanthan** [comment]
Hi @mattwilliamson I looked at your fork and believe you have refractored `duplicates.go` along with this bug fix. 
Does your fork combine solution to other bugs as I noticed changes to 
1. The uniqueness identifier 
2. Getting pods list on node 

Let me know if you are still working on this and need some help.

**Comment by hanumanthan** [comment]
Raised #334 for this issue
