### ISSUE TITLE
Make room for daemon sets

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/descheduler#303]
Sometimes daemon sets don't fit into existing nodes. In the case the descheduler should kill a pod which uses the least resources in order to allow the daemon set to run..

**Comment by seanmalloy** [comment]
/kind feature

I suppose this feature would require a new descheduler strategy to handle this use case.

@aveshagarwal @ingvagabund @damemi @ravisantoshgudimetla what do you think? Do you think it would make sense to implement a new descheduler strategy for this use case? Or is this outside the intended use case for the descheduler?

**Comment by ingvagabund** [comment]
@runningman84 would using preemption and priorities [1] solve your case? 

> In the case the descheduler should kill a pod which uses the least resources in order to allow the daemon set to run..

This is tricky since even when you evict a pod to free a space for daemon set pod, the scheduler can evict the daemon set pod in case a pod with higher priority needs to be scheduled.

[1] https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by seanmalloy** [comment]
/close

@runningman84 at this time we do not think it would be appropriate to add this feature to the descheduler. Please feel free to reopen this issue if you would like to continue the discussion. Thanks!

**Comment by unacceptable** [comment]
#783 to make a case for this again.
