### ISSUE TITLE
Use componentconfig api

### ISSUE THREAD

**Issue by damemi** [kubernetes-sigs/descheduler#431]
In https://github.com/kubernetes-sigs/descheduler/pull/380, we deprecated some component-level flags in favor of new policy config fields. Though, looking at our [ComponentConfig API](https://github.com/kubernetes-sigs/descheduler/blob/6240aa68f77a3e4f48413eb4c12962807b0b61da/pkg/apis/componentconfig/v1alpha1/types.go) I think adding them to policy might have been a duplicate.

However we don't seem to be using the ComponentConfig API anywhere now. We should determine a plan for this api and decide if we want to move ahead with using it or get rid of it (before we add any more component-level fields to the Policy api, if that's what we want to do)

**Comment by damemi** [comment]
Correction, we do use this API internally however I'm proposing that we expose it for external configuration as well

/cc @seanmalloy @ingvagabund 
@ravisantoshgudimetla or @aveshagarwal, could either of you provide some insight as to the original plan for the componentconfig api and if it was meant to be exposed?

**Comment by ingvagabund** [comment]
> could either of you provide some insight as to the original plan for the componentconfig api and if it was meant to be exposed?

As I recall, by the time the descheduler was delivered to this world, component config was the default way of configuring new components. The component config got serialized as a json/yaml and served through a config map that got attached to a container as a volume and passed to the component through `--config` (or its variation) flag.

Checking history of `cmd/descheduler/app/options/` I don't see CC has ever been passed to the descheduler through a flag.

> In #380, we deprecated some component-level flags in favor of new policy config fields. Though, looking at our ComponentConfig API I think adding them to policy might have been a duplicate.

`DeschedulerConfiguration` type's fields are currently used as value holder for various descheduler options. Thus the reason why those fields are duplicated. Given all three `--node-selector`, `--max-pods-to-evict-per-node` and `evict-local-storage-pods` are deprecated, `NodeSelector`, `MaxNoOfPodsToEvictPerNode` and `EvictLocalStoragePods` fields are deprecated as well and will get removed eventually. So the duplication is only temporary for [12 months or 2 releases (whichever is longer) since the deprecation was announced](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli).

> However we don't seem to be using the ComponentConfig API anywhere now. We should determine a plan for this api and decide if we want to move ahead with using it or get rid of it (before we add any more component-level fields to the Policy api, if that's what we want to do)

Depends on which component-level field is to be added. Anything related to strategies goes to the Policy API, everything else to CLI options/CC fields. [Versioned Component Configuration Files](https://docs.google.com/document/d/1FdaEJUEh091qf5B98HM6_8MS764iXrxxigNIdwHYW9c/edit#) gives good reasons to prefer CC over flags.

+1 for keeping CC and adding new `--config` option.

**Comment by damemi** [comment]
> Given all three --node-selector, --max-pods-to-evict-per-node and evict-local-storage-pods are deprecated, NodeSelector, MaxNoOfPodsToEvictPerNode and EvictLocalStoragePods fields are deprecated as well and will get removed eventually.

Those flags are deprecated, but the configuration options shouldn't be, right? So those would be configurable by CC

**Comment by damemi** [comment]
In other words, we deprecated the ability to pass node-selector as a flag but we aren't trying to get rid of that option entirely

**Comment by ingvagabund** [comment]
> Those flags are deprecated, but the configuration options shouldn't be, right? So those would be configurable by CC

> In other words, we deprecated the ability to pass node-selector as a flag but we aren't trying to get rid of that option entirely

That is correct

**Comment by damemi** [comment]
Ok, just wanted to clarify. Yeah in that case the duplication isn't a problem, thanks for clearing that up. I don't see any reason not to revive CC then

**Comment by seanmalloy** [comment]
> +1 for keeping CC and adding new `--config` option.

I'm good with this too.

**Comment by damemi** [comment]
/remove-lifecycle stale
This came up again in some other PRs like https://github.com/kubernetes-sigs/descheduler/pull/662
We should decide what to do with the CC types. At this point, they are just redundant for all the config values we have in Policy.

I think you could make a case that the CC should be just component-specific settings while Policy has the settings for individual strategies. But is that a functional improvement and is the change worth it for users?

Perhaps we should look at just removing the CC types altogether to clean up the code. Any thoughts either way?

**Comment by ingvagabund** [comment]
If we drop the CC code we can always put it back once it becomes relevant. We might eventually promote the policy into the CC?
