### ISSUE TITLE
RemoveDuplicates: take taints and node selector into account when computing the number of duplicates

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes-sigs/descheduler#551]
**Is your feature request related to a problem? Please describe.**
In case there's a cluster with 3 master nodes and 3 workers and a workload (owned by an RC) is uniformly distributed among worker nodes (the expected distribution), the strategy still evicts pods of the workload since it takes master nodes into account as well. E.g. 12 pods, 4 pods bound to each worker node, 6 pods are evicted (6 nodes, 12 pods, 2 per node) which always end up on the same worker nodes again.

**Describe the solution you'd like**
Take at least node taints (e.g. taints repealing pods from master nodes) into account when selecting pods for eviction. If possible, take node selector into account as well.

**Describe alternatives you've considered**
Not considered

**What version of descheduler are you using?**
The latest master HEAD

descheduler version:
Assume 0.20

**Additional context**

**Comment by damemi** [comment]
We could probably open an umbrella issue to get all strategies in line with this. I also have https://github.com/kubernetes-sigs/descheduler/issues/529 for LNU and @RyanDevlin pointed out the same with Affinity and PTS https://github.com/kubernetes-sigs/descheduler/issues/529#issuecomment-820393845

**Comment by RyanDevlin** [comment]
It seems like this could be implemented as a global feature in `evictions.go`. Maybe there could be a modification to the Evictable function to take the context of cluster nodes into account. So instead of:
```
func (pe *PodEvictor) Evictable(opts ...func(opts *Options)) *evictable {}
```

We have: 
```
func (pe *PodEvictor) Evictable(nodes []*v1.Node, opts ...func(opts *Options)) *evictable {}
```

Inside this function (possibly with a call to a utility function), the node taints and pod tolerations, RequiredDuringSchedulingIgnoredDuringExecution affinity rules, and node selectors could be checked. All the strategies would most likely need to be modified after this addition to __not check__ affinity rules or taints if they already do.

This way, the optimization is globally implemented. Thoughts on this approach?

**Comment by damemi** [comment]
The `PodEvictor` already has [the list of nodes](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/evictions/evictions.go#L64), so we shouldn't need to pass it to `Evictable`. So we could just enable the check using the `WithOption...` pattern (like in [NodeAffinity](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/strategies/node_affinity.go#L81-L88))

I don't think this should be enabled by default, because we do allow evicting pods without Owners (ie, pods that won't get recreated), so in those cases whether or not a pod fits on another node is irrelevant. That means this will probably have to be exposed as a policy option

**Comment by damemi** [comment]
> Good point, I didn't notice the `PodEvictor` already had that. I'm a bit confused about the second part of your comment though. As I understand we've hardcoded the `IsEvictable()` function in `evictions.go` to never evict pods without `ownerRefs`, no?

Any pod with the [`descheduler.alpha.kubernetes.io/evict` annotation](https://github.com/kubernetes-sigs/descheduler#pod-evictions) can be evicted, regardless of ownerRefs (checked in [evictions.go](https://github.com/kubernetes-sigs/descheduler/blob/b5d7219/pkg/descheduler/evictions/evictions.go#L259)

**Comment by RyanDevlin** [comment]
Oh right! Okay in that case, I'm happy to work on this one. Should I open another issue as a catch-all referencing this one and #529?

**Comment by RyanDevlin** [comment]
@ingvagabund @damemi I'm assuming this is out of scope for the issue, but I thought I'd still bring it up. Should considerations be made to the various other scheduling predicates that are used by the scheduler in filtering? For instance, with predicates like `PodFitsResources` or `NoDiskConflict`, the scheduler is able to filter out nodes that will not be able to run this pod. If we don't take that into account when evicting, there's a probability that the pod will just be rescheduled onto the same node, and we will have disrupted a workload for no reason.

On the flip side of this, maybe the descheduler is meant to be run at times when disrupting workloads is acceptable (eg. overnight), and therefore this consideration is not needed. Is this a valid concern?

**Comment by ingvagabund** [comment]
Until the scheduling framework (or its key part) is completely moved under a staging repo, it will be an overkill to take into account every plugin with Filter method. We are aware of this limitation. For the moment we can only improve the estimation on how many nodes are "free" for scheduling. Eventually, the Descheduler will run a subset of the scheduler through various plugins (which will be probably configured at the startup). Though, there's still gonna be chance a pod gets re-scheduled to the same node no matter how good estimate we will make.

> On the flip side of this, maybe the descheduler is meant to be run at times when disrupting workloads is acceptable (eg. overnight), and therefore this consideration is not needed. Is this a valid concern?

I like to keep this decision for consumers :)

**Comment by RyanDevlin** [comment]
@ingvagabund @damemi In terms of how this feature may be extended in the future, do we want the ability to selectively include some, but not all, of the filtering methods? For instance, right now I have checks for NodeAffinity, NodeSelector, and Taints. I can design the feature such that the descheduler can be configured to check for all of these, or check for a subset, like NodeSelector and Taints.

To enable all filters, this would look like:
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
     params:
       removeDuplicates:
         excludeOwnerKinds:
         - "ReplicaSet"
         predicates:            <========= Here
         - "All"
```


To enable a subset, it would look like:
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemoveDuplicates":
     enabled: true
     params:
       removeDuplicates:
         excludeOwnerKinds:
         - "ReplicaSet"
         predicates:            <========= Here
         - "MatchNodeSelector"
         - "PodToleratesNodeTaints"
```

I'm uncertain whether we wanted this to be an "all or nothing" parameter?

**Comment by damemi** [comment]
That's an interesting idea, but I would start with all or nothing for now, before going to that level of granularity (since we don't currently have any reported use cases for being that much detail)

In the future, I think at most that level of detail could simply be a top-level setting that applies to all strategies

**Comment by RyanDevlin** [comment]
@damemi Okay good point. For now I'll just build it as a boolean parameter for all strategies.
