### ISSUE TITLE
Missing image v0.21.0

### ISSUE THREAD

**Issue by eon01** [kubernetes-sigs/descheduler#555]
It seems that the last image was not pushed (v0.21.0):

```
docker pull k8s.gcr.io/descheduler/descheduler:v0.21.0
Error response from daemon: manifest for k8s.gcr.io/descheduler/descheduler:v0.21.0 not found: manifest unknown: Failed to fetch "v0.21.0" from request "/v2/descheduler/descheduler/manifests/v0.21.0".
```

```
docker pull k8s.gcr.io/descheduler/descheduler:v0.20.0
v0.20.0: Pulling from descheduler/descheduler
120737647dc7: Pull complete 
```

**Comment by damemi** [comment]
The `v0.21.0` image has not been published yet. We are currently waiting on Kind to publish their 1.21 release so that our CI can accurately test against it. Please see the 0.21 tracking issue for more information: https://github.com/kubernetes-sigs/descheduler/issues/491#issuecomment-818933863
/close
