### ISSUE TITLE
HighNodeUtilization README.md is duplication of LowNodeUtilization

### ISSUE THREAD

**Issue by chrisjohnson00** [kubernetes-sigs/descheduler#591]
Much of the HighNodeUtilization documentation in the README.md is a copy/paste from LowNodeUtilization with /s/Low/High replaced.  Other than the type change, the documentation is incorrect as it's a copy of Low Node's threshold functionality.

```
HighNodeUtilization

This strategy finds nodes that are under utilized and evicts pods in the hope that these pods will be scheduled compactly into fewer nodes. This strategy must be used with the scheduler strategy MostRequestedPriority. The parameters of this strategy are configured under nodeResourceUtilizationThresholds.
```

The above example explains what I mean, where it says it 

> ...finds nodes that are under utilized and evicts pods in the hope that these pods will be...

I don't know the inner workings of descheduler to propose this documentation update, but if other contributors are willing to review my PR with that in mind, I'd be willing to give it a crack at correcting it (LMK)

**Comment by damemi** [comment]
Hi @chrisjohnson00,
The wording for the 2 strategies is very similar, because under the hood they are essentially the same functions with an invert. However I don't think the section you shared is incorrect:

> This strategy finds nodes that are under utilized and evicts pods in the hope that these pods will be scheduled compactly into fewer nodes.

For HighNodeUtilization, this means that it is looking for nodes that are *under* the utilization thresholds and evicts pods *from those nodes* to compact them onto *other* nodes

> This strategy finds nodes that are under utilized and evicts pods, if possible, from other nodes in the hope that recreation of evicted pods will be scheduled on these underutilized nodes

This is the matching section from LowNodeUtilization, which means that while it is still looking for nodes that are *under* the thresholds, it is instead evicting pods from *other* nodes onto those under utilized nodes.

This could probably be worded better in the docs though, so if you have the time to improve them then please feel free to submit a PR 🙂

**Comment by seanmalloy** [comment]
Docs have been updated in #592.

/close
