### ISSUE TITLE
Helm: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"

### ISSUE THREAD

**Issue by Svisstack** [kubernetes-sigs/descheduler#593]
**What version of descheduler are you using?**

descheduler version: latest from the helm chart.

**Does this issue reproduce with the latest release?**

Yes.

**Which descheduler CLI options are you using?**

No options.

**Please provide a copy of your descheduler policy config file**

No policy.

No policy.

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What did you do?**

```
~# helm install descheduler --namespace kube-system descheduler/descheduler
```

**What did you expect to see?**

Information that helm chart was installed.

**What did you see instead?**

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"
```

**Comment by damemi** [comment]
@Svisstack sorry, I saw your comment in the PR before I saw this issue. I think the problem is that you are using the latest (1.21) descheduler helm chart on an older version of kubernetes (1.19). CronJobs were promoted to v1 in the 1.21 release so we updated the helm chart to use that version by default.

@Svisstack no, this PR is to add a new version for the Descheduler's own config API

You can set the [`cronJobApiVersion` value in the helm chart](https://github.com/kubernetes-sigs/descheduler/blob/f07089d7b377a49f3d52362e581138d83c453715/charts/descheduler/values.yaml#L22) to `batch/v1beta1` if you would like to use the latest chart on k8s <1.21

**Comment by Svisstack** [comment]
Thanks.
