### ISSUE TITLE
Can I schedule only based on memory

### ISSUE THREAD

**Issue by songwenchaols** [kubernetes-sigs/descheduler#625]
能不能只依据内存进行调度，同时满足cpu  内存  pod数的条件有点太苛刻了，生产中很不容易找到平衡点，有的pod内存很大，导致内存溢出了，pod数始终没有达到阈值，cpu也没有达到阈值，也就没有办法触发调度。

**Comment by disparo13** [comment]
Can you write in English?

**Comment by songwenchaols** [comment]
Can you schedule only the memory and meet the condition of CPU memory number is too poor. It is easy to find a balance point in production. Some pods have large memory, resulting in memory. The number of pods always does not reach the threshold, the CPU does not reach the critical value, and there is no way to trigger scheduling.

**Comment by songwenchaols** [comment]
I use google translate

**Comment by songwenchaols** [comment]
CPU memory pod ，Judge memory only，how？

**Comment by disparo13** [comment]
@songwenchaols try to set both `thresholds` and `targetThresholds` to 100% in your policy.

**Comment by songwenchaols** [comment]
> @songwenchaols尝试在您的策略中将 cpu`thresholds`和`targetThresholds`cpu 值都设置为 100%。
no way

**Comment by disparo13** [comment]
@songwenchaols if no way - then no memory management, that's simple

**Comment by miaojianbin** [comment]
I have the same problem. Our applications used many memory ,but little cpu. 
Example: I have two nodes :

NAME         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k8s-work1    821m         51%    14666Mi         100%      
k8s-work2    544m         38%    12151Mi         89%


If I want to move pods of k8s-work1 to k8s-work2, I config like this:
```
         thresholds:
           "cpu" : 100
           "memory": 90
           "pods": 100
         targetThresholds:
           "cpu" : 100
           "memory": 90
           "pods": 100
```
It doesn't work. Number of overutilized nodes is 0 , Because CPU&PODS of all the nodes is not overutilized ,not above 100%.
The LOG:
```
I0211 09:01:19.854328       1 lownodeutilization.go:99] "Criteria for a node under utilization" CPU=100 Mem=90 Pods=100
I0211 09:01:19.854355       1 lownodeutilization.go:100] "Number of underutilized nodes" totalNumber=10
I0211 09:01:19.854369       1 lownodeutilization.go:113] "Criteria for a node above target utilization" CPU=100 Mem=90 Pods=100
I0211 09:01:19.854378       1 lownodeutilization.go:114] "Number of overutilized nodes" totalNumber=0
I0211 09:01:19.854394       1 lownodeutilization.go:127] "All nodes are underutilized, nothing to do here"
```

I just want to evicts pods only by memory ,ignore the cpu and pods. Is there any other way?
