### ISSUE TITLE
Eviction enhancement

### ISSUE THREAD

**Issue by JaneLiuL** [kubernetes-sigs/descheduler#626]
**Background**: 
I try to install descheduler into my k8s cluster, the cluster only have two nodes, one is master, another is worker node.
Then I create a deployment with **6** replicas, I try to open the log with descheduer, then I always see one pod will be Evict again and again from the same node. 
**Question**:
```
I0913 11:11:10.417814       1 event.go:291] "Event occurred" object="default/nginx-deployment-66b6c48dd5-pz8jv" kind="Pod" apiVersion="v1" type="Normal" reason="Descheduled" message="pod evicted by sigs.k8s.io/deschedulerRemoveDuplicatePods"
I0913 11:11:10.429113       1 pod_antiaffinity.go:81] "Processing node" node="nodeNamexxx"
I0913 11:11:10.440102       1 descheduler.go:152] "Number of evicted pods" totalEvicted=1
```
**How to resolve?**
As we have no idea how to scheduler will be scheduled pod(since different user may have their self developer schedule plugins) So could we just cache the evict information to avoid the eviction again and again, like below? 

Each time before we evict a pod,  we will record the pod nodeName, ownerReference Key 
Then before we evict the pod from the nodeName, we will check is it this pod(ownerReference Key is the same, nodeName is the same), to check the Pod is it evict from this Node in 10 minutes.
If yes, then we will not evict, for the scheduler may schedule to the Same Node again.
If no, then we will try to evict, and record it into the cache.

How do you think so?

**Comment by damemi** [comment]
This is an interesting proposal! I think some option to add an exponential backoff for pod re-eviction could be useful to prevent spam. However it will only really be useful in clusters with changing conditions, because if nothing changes between each backoff we are only delaying the inevitable (the pod will get evicted again).

In cases like this, it is usually recommended for the administrator to look at why the same pod is getting evicted over and over. For example, are there hard affinity rules on the pod that are requiring it to go to a certain node? Settings like this could conflict with descheduler strategies, so in some cases this feature could just hide symptoms of a suboptimal cluster configuration.
