### ISSUE TITLE
Delete evicted status pods

### ISSUE THREAD

**Issue by ichasco-heytrade** [kubernetes-sigs/descheduler#651]
Hi I would like to know if evicted status pods can be deleted with descheduler. 

Example:
```
cert-manager-79d879cf69-5tkqq              0/2     Evicted   0          8h
```

I would like to delete this pod.

Thanks

**Comment by ingvagabund** [comment]
As @damemi pointed out, not much the descheduler can do about deleting a pod. The descheduler relies on the evict subresource. Anything beyond is out of reach of the descheduler. If the pod is owned by a job (or other controller capable or re-creating pods) it may be necessary to remove the job as well. Otherwise, the pod is expected to get deleted eventually.

/close
