### ISSUE TITLE
After pod is evicted ,it's restarted at the original node

### ISSUE THREAD

**Issue by qingtianlanyue** [kubernetes-sigs/descheduler#655]
**What version of descheduler are you using?**

descheduler version:
v0.22

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**

The default configuration
![image](https://user-images.githubusercontent.com/41791726/141884751-632ab337-b185-4b9a-a1a8-3377d3b033cd.png)

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by ingvagabund** [comment]
Once a pod is evicted by the descheduler, it's up to the control plane to properly evict the pod. If a pod is restarted on the original node, something wrong is happening on the kubelet. I recommend to either reach out to #sig-node on the Kubernetes slack or open an issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/issues).

/close

**Comment by damemi** [comment]
This could also be referring to the new pod being rescheduled on the same node, not specifically the exact some pod being restarted by the kubelet.

However if that's the case, there is still nothing the descheduler can do to handle it. This is because the pod is not "restarted", the pod you're seeing on the same node is an entirely different pod that has been newly created when the old pod was evicted by the descheduler. As such, descheduler has no knowledge about this pod.

The way to resolve this is to ensure that your descheduler settings are aligned with the settings of your scheduler, and investigate into the scheduler why it is scheduling new pods onto nodes which are unfit. You can cross-reference this to the eviction reason the descheduler logs for the original pod.
