### ISSUE TITLE
Add support for nodeName 

### ISSUE THREAD

**Issue by yasintahaerol** [kubernetes-sigs/descheduler#705]
**Is your feature request related to a problem? Please describe.**

We use nodeName option instead of nodeSelector. Then, we realize there was no support for nodeName.

**Describe the solution you'd like**

If nodeSelector null or empty, check the nodeName. 
For example function: 
```
func HasOwnerNodeName(client clientset.Interface, pod *v1.Pod) bool {
	owner := podutil.OwnerRef(pod)[0]
	switch owner.Kind {
	case "ReplicaSet":
		replica, _ := client.AppsV1().ReplicaSets(pod.Namespace).Get(context.TODO(), pod.OwnerReferences[0].Name, metav1.GetOptions{})
		return replica.Spec.Template.Spec.NodeName != ""
	case "<OTHER KINDS>":
		return false
	}
	return false
}
```
**Describe alternatives you've considered**

**What version of descheduler are you using?**

descheduler version: v0.22.1

**Additional context**
cc: @Dentrax @eminaktas @developer-guy

**Comment by Dentrax** [comment]
Addition to this proposal, there may be some concerns that we should consider:
* in the `getTargetNodes()` function loop, we are traversing all pods and `HasOwnerNodeName` function request an API call to API Server in order to get _owner object_ of the given pod. This would cause heavily API load to cluster. To tackle this problem, we should not _do_ additional call to `HasOwnerNodeName()` function in case `nodeSelected` already passed. (will slightly decrease the overall load)
* pod can be _static_. in this case pod does not have an _owner_. we can return `false` in this case.

**Comment by ingvagabund** [comment]
@yasintahaerol would you mind to elaborate more on the use case? I am out of context here. @Dentrax mentioned `getTargetNodes()` function which is used in the `RemoveDuplicatePods` strategy but I still do not follow.

**Comment by Dentrax** [comment]
We currently check the only `nodeSelector` field, but we can also add support for `nodeName` field. We had to debug the Descheduler manually and finally figured out that `nodeName` not supported.

**Comment by cortopy** [comment]
I'm also experiencing this issue. @ingvagabund I'm not sure if the other users meant the same thing, but this is what's happening in my case:

- some statefulsets use local storage drivers (openebs local zfs in this case)
- the pod won't have a `nodeSelector`, but a `nodeName`
- I have a statefulset with two replicas and the second replica keeps getting evicted because of `RemoveDuplicatePods` rule

The goal would be to detect that this is false positive and the pod is not evicted

**Comment by Dentrax** [comment]
/remove-lifecycle stale
/remove-lifecycle rotten

> It sounds like the ask is to be able to exclude a pod from eviction if it has a nodeName set?

That's right!

> That might be difficult since every scheduled pod is going to have a nodeName set...

What if it's a _static_ Pod?
