### ISSUE TITLE
MostAllocated scheduler strategy

### ISSUE THREAD

**Issue by bwmetcalf** [kubernetes-sigs/descheduler#749]
We have the descheduler working with the `HighNodeUtilization` strategy and it's successfully evicting pods.  However, the pods get re-scheduled on the same node from which they were evicted and I assume this is because we don't yet have in place a `MostAllocated` scheduler strategy describe here: https://github.com/kubernetes-sigs/descheduler#highnodeutilization.

We are using EKS and terraform.  Does anyone have any pointers on what a `MostAllocated` config should look like and a process for installing it?  Do we replace the default scheduler or add a second one?

Thanks.

**Comment by JaneLiuL** [comment]
hi， for the scheduler it is plugin call `NodeResourcesFit`  you can refer via https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins, by default it is `LeastAllocated`, you need to add the config as below:
```
```

**Comment by damemi** [comment]
@bwmetcalf you are correct that the pods are likely landing on the same node due to not configuring the MostAllocated strategy. By default, the scheduler tries to spread pods onto the least-allocated nodes.

You need to apply a scheduler configuration like @JaneLiuL shared to enable this strategy. If EKS won't allow you to modify the default scheduler deployment (to set the `--config` flag pointing to your config), you may need to run a custom scheduler.

**Comment by bwmetcalf** [comment]
Thanks for the feedback @damemi and @JaneLiuL.  This is related to https://github.com/kubernetes-sigs/descheduler/issues/750.  Getting into the depths of the k8s scheduler seems like it may have unintended consequences.  Our thought is if https://github.com/kubernetes-sigs/descheduler/issues/750 is addressed and the descheduler will evict pods that don't tolerate the `PreferNoSchedule` taint, then the default k8s scheduler will attempt to re-schedule the pods on our "base" nodes without this taint (nodes not spun up by karpenter) first and only re-schedule on the nodes we are looking to drain with the `HighNodeUtilization` as a last resort.

**Comment by bwmetcalf** [comment]
I think that is opposite of what we are trying to achieve.  Here is our setup and use case.  We have "base" nodes that are configured as part of our eks cluster; these nodes have no taints.  We then install karpenter to respond to unschedulable pods; these nodes have a `PreferNoSchedule` taint.  In order to drain the "karpenter" nodes so that they can be terminated by karpenter based on the `ttlSecondsAfterEmpty` setting, we want the descheduler to evict pods from these nodes even if they don't tolerate the `PreferNoSchedule` taint.  Then, the default k8s scheduler can do its thing and attempt to schedule the evicted pods on the "base" nodes and only use the tainted "karpenter" nodes as a last resort.  This seems much less intrusive than getting into installing and maintaining a customer scheduler.

I believe this will work if https://github.com/kubernetes-sigs/descheduler/issues/750 is addressed.

**Comment by damemi** [comment]
@bwmetcalf Yep, #750 will resolve the problem you're seeing where descheduler does not currently evict pods that violate the `PreferNoSchedule` taint on their current node. The scheduler config I was referring to will fix your concern about the pods being re-scheduled onto the same nodes, since re-scheduling is beyond the descheduler's control. Sorry if I misunderstood what you were saying
