### ISSUE TITLE
descheduler uses a lot of memory when cluster is large

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/descheduler#774]
**What version of descheduler are you using?**

descheduler version: k8s.gcr.io/descheduler/descheduler:v0.23.0

**Does this issue reproduce with the latest release?**
yes

**Which descheduler CLI options are you using?**
https://github.com/matti/eksler/blob/496530189c5ad82f9a7d62d4e192f83bdf7ae277/helm/charts/descheduler-1/values.yml

**Please provide a copy of your descheduler policy config file**
see above

**What k8s version are you using (`kubectl version`)?**

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Installed descheduler chart v0.23.1 with values https://github.com/matti/eksler/blob/496530189c5ad82f9a7d62d4e192f83bdf7ae277/helm/charts/descheduler-1/values.yml

**What did you expect to see?**

Descheduler not to use tons of memory

**What did you see instead?**

Descheduler uses 753Mi memory with 261 nodes and 5700 running pods out of 15000 pods. the chart default value is 256Mi

```
$ kubectl top pod -n descheduler-1
NAME                             CPU(cores)   MEMORY(bytes)   
descheduler-1-6fdcdf644f-q2wht   91m          753Mi 
```

when it was left running it eventually dropped to 434Mi which is still larger than the chart default value

**Comment by JaneLiuL** [comment]
hi @matti  since you are use the helm charts to deploy

**Comment by matti** [comment]
I believe that the Job will still consume a lot of memory, but I'll test

**Comment by damemi** [comment]
@matti just to clarify, @JaneLiuL is saying that you should run it as a Deployment (not a Job or CronJob). The Deployment has a descheduling interval flag that keeps a single pod running rather than creating a new one each time.

I do agree that this will likely still face similar memory issues which we need to profile and debug. But it will be good to have the comparison just as a starting point

**Comment by damemi** [comment]
If you have it running as a deployment, that should give us an idea of the long-running usage, yeah. 10s is a pretty short cycle length, especially for a large cluster. But I think the point we need to focus on is figuring out what is using that much memory. If it's just the pod/node cache, I don't know if there's much we can do about that since that's a client we just import. 

But it's possible (likely) that some of our strategy implementations are doing big in-memory representations of the cluster state. If you're just using the policy you linked above (https://github.com/matti/eksler/blob/496530189c5ad82f9a7d62d4e192f83bdf7ae277/helm/charts/descheduler-1/values.yml#L46-L82) then we should start there.

If you have time, maybe you could give a shot only running a policy with one of these strategies enabled at a time? Tracking the memory usage per strategy might help us narrow down what are the worst offenders. I suspect `LowNodeUtilization` might be a big offender since it tracks pods and nodes.

**Comment by damemi** [comment]
Fyi I opened https://github.com/kubernetes-sigs/descheduler/issues/782 to track an effort to add performance tests so we can work on things like this.
