### ISSUE TITLE
Use a cron interval for deployments

### ISSUE THREAD

**Issue by jklaw90** [kubernetes-sigs/descheduler#784]
**Is your feature request related to a problem? Please describe.**

The deployment is hard to predict when it'll run since its based of an interval that starts when it's deployed.
This make it hard to test / predict when it'll run especially if the interval is larger.

**Describe the solution you'd like**

I think we should be using a cron syntax even for the deployment.
https://github.com/robfig/cron is already used in the k8s cronjob controller.
Ideally this can be overridden per strategy but this may be default with a cron deployment users may use.

**Describe alternatives you've considered**
Currently keeping the cron running more often than i'd like to be able to ensure its running properly in smoke tests.

**What version of descheduler are you using?**

descheduler version:  1.23

**Additional context**

**Comment by a7i** [comment]
This could lead to potential misses, e.g. when a Kubernetes Pod is rescheduled right when it's supposed to get triggered. Also, another external dependency when Kubernetes offers robust cron capabilities.

I assume you don't want to use a CronJob because of metrics scraping? If that is the case, it seems better to use the built-in Kubernetes CronJob but allow of a termination grace to ensure all metrics can be scraped before shutting down.

**Comment by jklaw90** [comment]
good point i guess we'd need external state to save last run or run on boot 🤔.
