### ISSUE TITLE
Looks like 0.24.0 helm chart release missing

### ISSUE THREAD

**Issue by sergeyshevch** [kubernetes-sigs/descheduler#800]
**What version of descheduler are you using?**

descheduler version: 0.23

**Does this issue reproduce with the latest release?**

**Which descheduler CLI options are you using?**

**Please provide a copy of your descheduler policy config file**

**What k8s version are you using (`kubectl version`)?**

1.22

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**

**What did you expect to see?**

0.24.0 chart released. I want to setup HA and leader election in it

**What did you see instead?**

**Comment by damemi** [comment]
Hi @sergeyshevch 
The v0.24.0 helm chart has not been released yet. The `master` branch is updated with this version number because we are currently in the process of publishing the release. You can follow the status of the release in [this issue](https://github.com/kubernetes-sigs/descheduler/issues/735), and check https://artifacthub.io/packages/helm/descheduler/descheduler which will be updated when the v0.24 helm chart is finally released. This should be ready by the end of the week.

For future reference, the `master` branch should be considered in-development, with the `release-*` branches considered as the official release number. Apologies for the confusion.
/close
