### ISSUE TITLE
No docker image for chart version v0.24.1

### ISSUE THREAD

**Issue by amadeusjposchmann** [kubernetes-sigs/descheduler#822]
**What version of descheduler are you using?**

descheduler version: helm-chart v0.24.1

**Does this issue reproduce with the latest release?**
Yes

**Which descheduler CLI options are you using?**
Chart default, running as Deployment

**Please provide a copy of your descheduler policy config file**
Chart's default

**What k8s version are you using (`kubectl version`)?**
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"8211ae4d6757c3fedc53cd740d163ef65287276a", GitTreeState:"clean", BuildDate:"2022-03-31T20:28:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Update Helm chart from v0.24.0 to v0.24.1

**What did you expect to see?**
Release upgrades to v0.24.1

**What did you see instead?**

```
Warning  Failed     36m (x4 over 38m)      kubelet            Failed to pull image "k8s.gcr.io/descheduler/descheduler:v0.24.1": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/descheduler/descheduler:v0.24.1": failed to resolve reference "k8s.gcr.io/descheduler/descheduler:v0.24.1": k8s.gcr.io/descheduler/descheduler:v0.24.1: not found
```

**Comment by sebastiangaiser** [comment]
@damemi is the build already running?

At least in my opinion, the order should be:
1. Build and publish container image
2. Bump Helm chart to new version

**Comment by michelefa1988** [comment]
Following as well, still have this issue

**Comment by damemi** [comment]
Apologies. For full transparency of the current issue, our release process involves a number of automated and manual steps which you can read about in our [release guide](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md). During the past release cycle, we discovered [issues](https://github.com/kubernetes-sigs/descheduler/issues/736) with our image tagging steps due in part to the automated release steps (mostly, the Helm chart releaser action that publishes the updated Helm chart versions).

This is now documented in the release guide, and discussed in the issue I linked above, but the tl;dr is that in order to get a published container image of the descheduler that produces the right version output, we need to `git tag` that release before merging a PR that triggers an automatic image build. In order to get all of the relevant "functional" code into that version's `git tag`, we decided to reserve that last PR for the Helm chart update. This provides us with an automated image SHA that we can promote upstream the `k8s.gcr.io` registry.

For this particular release (v0.24.1) we also started hitting timeouts in the automated builds (https://github.com/kubernetes-sigs/descheduler/pull/825).

Due to these constraints between our own automation and k8s infra it is, unfortunately, not as simple as:

> 1. Build and publish container image
> 2. Bump Helm chart to new version

However we are taking this release to sort out these issues and attempt to streamline the process for future releases. In that effort, I am open to suggestions or effective contributions to improve the release process. Ideally, we would have one automatic step that tags a release, promotes the container image through k8s infra, updates our Helm chart on ArtifactHub, and publishes the Github release simultaneously.

I am sorry for the delay and am working on resolving this release asap

**Comment by damemi** [comment]
v0.24.1 image promotion PR created upstream: https://github.com/kubernetes/k8s.io/pull/3793

Sorry again for the inconvenience. This issue should be resolved once that PR merges, thanks everyone!

**Comment by damemi** [comment]
Image looks available now:
```
$ docker run k8s.gcr.io/descheduler/descheduler:v0.24.1 descheduler version
Unable to find image 'k8s.gcr.io/descheduler/descheduler:v0.24.1' locally
v0.24.1: Pulling from descheduler/descheduler
Digest: sha256:c8d726c48d83d479f83519bdbac0f5aa4a95af2b256db1c8fc86ea3d0ae9f8df
Status: Downloaded newer image for k8s.gcr.io/descheduler/descheduler:v0.24.1
Descheduler version {Major:0 Minor:24.1 GitVersion:v20220601-descheduler-helm-chart-0.24.1-3-g9bf473b7e GitBranch: GitSha1: BuildDate:2022-06-01T14:26:48+0000 GoVersion:go1.18.2 Compiler:gc Platform:linux/amd64}
```

/close
