### ISSUE TITLE
New release - latest is from May 31

### ISSUE THREAD

**Issue by bwmetcalf** [kubernetes-sigs/descheduler#930]
Can a new release be created for this project?  The last tagged release is from May 31.

**Comment by damemi** [comment]
Hi @bwmetcalf, we publish a new release for each Kubernetes release (and critical patches in the meantime). See our tracking issue for this release https://github.com/kubernetes-sigs/descheduler/issues/844

Since v0.25.0 was just published we are working on the steps for the [release process](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md) right now. The new release will be available in the next few weeks, but may be slightly delayed with in-flight refactoring PRs for the framework effort.

Closing this issue to keep release discussion in the pinned #844, thanks!
/close
