### ISSUE TITLE
Proposal: Support for Backward Compatibility

### ISSUE THREAD

**Issue by Dentrax** [kubernetes-sigs/descheduler#950]
**Is your feature request related to a problem? Please describe.**
AFAIK, Descheduler does not have a hard dependency to a _specific_ Kubernetes release. However, a particular Descheduler release is only tested against the _three_ latest Kubernetes minor versions. [^1]

**Describe the solution you'd like**

* Do not break the backward compatibility after starting Descheduler version _X_.
* Redesign Compatibility Matrix in README
* Have matrix E2E testing

**X:** TBD

**Concerns and Problems**

* **Problem 1:** Compatibility Matrix could misguide the end user in the first place. That's being said, it seem like we should NOT install Descheduler `< v0.25` if we are running Kubernetes `v1.25`.
* **Solution:** Extend the compatibility matrix to indicate we actually support latest 3 Kubernetes minor releases. See the example designs below:

Design 1: Minor Versions

Descheduler | Supported Kubernetes Versions
---------------|---------------------------
v0.24          | v1.24.3, v1.24.4, v1.24.5
v0.24          | >= v1.24.3

* **Problem 2:** What we say in the README: _"However a particular descheduler release is only tested against the three latest k8s minor versions."_ could be a bit confusing in the first place. Is that means, for example Descheduler `v0.24`, are we run tests against `[v1.24.3, v1.24.4, v1.24.5]` or `[v1.22, v1.23, v1.24]`? (Are we really _do_ matrix testing? Please see another problem below.)
* **Solution:** Consider rephrasing clearly the following above sentence in the README to indicate what we actually run tests for. Eventually we would end up in a new capability matrix design:

Design 2: Major Versions

Descheduler | v1.21 | v1.22 | v1.23 | v1.24 | v1.25
------------|-------|-------|-------|-------|-------|
v0.25       |   -   |   -   |   X   |   X   |   X   |
v0.24       |   -   |   X   |   X   |   X   |   -   |
v0.23       |   X   |   X   |   X   |   -   |   -   |

* **Problem 3:** E2E tests only run for single `KUBERNETES_VERSION` in both [helm.yaml](https://github.com/kubernetes-sigs/descheduler/blob/59834cf8a72e4fe55c5e2a325404c934b042cc87/.github/workflows/helm.yaml#L62-L67) and [run-e2e-tests.sh](https://github.com/kubernetes-sigs/descheduler/blob/59834cf8a72e4fe55c5e2a325404c934b042cc87/test/run-e2e-tests.sh#L28).
* **Solution:** Use [matrix testing](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) in both GitHub Actions and E2E tests to fulfill the aforementioned statement: at least we should run tests against _3 last_ Kubernetes _minor/major?_ versions in matrix manner.

1. If we want to support _one major_ Kubernetes version, I think we should _also_ test the all subsequent minor versions. For example, If we want to say _"Descheduler v0.24 support Kubernetes v1.24"_, should better to run a matrix test against `[v1.24, v1.24.1, v1.24.2, v1.24.3, v1.24.4, v1.24.5]`.

2. If we want to support _more than one major_ Kubernetes versions, then we should do _matrix in matrix_ test. For example, if we want to support last 2 major Kubernetes releases, shouldn't we do test each minor versions that included in `v1.23`, and then test each minor versions that included in `v1.24`?

**Describe alternatives you've considered**

**What version of descheduler are you using?**
`-`

**Additional context**
`-`

cc @eminaktas 

[^1]: https://github.com/kubernetes-sigs/descheduler#compatibility-matrix

**Comment by damemi** [comment]
> * **Problem 1:** Compatibility Matrix could misguide the end user in the first place. That's being said, it seem like we should NOT install Descheduler `< v0.25` if we are running Kubernetes `v1.25`.
> * **Solution:** Extend the compatibility matrix to indicate we actually support latest 3 Kubernetes minor releases. See the example designs below:
> 
> Design 1: Minor Versions
> 
> Descheduler	Supported Kubernetes Versions
> v0.24	v1.24.3, v1.24.4, v1.24.5
> v0.24	>= v1.24.3

Could you give another example of the compatibility you mean? By `it seem like we should NOT install Descheduler < v0.25 if we are running Kubernetes v1.25`, it sounds like you're asking for forward-compatibility such as running descheduler `v0.24` on k8s `v1.25`. 

> * **Problem 2:** What we say in the README: _"However a particular descheduler release is only tested against the three latest k8s minor versions."_ could be a bit confusing in the first place. Is that means, for example Descheduler `v0.24`, are we run tests against `[v1.24.3, v1.24.4, v1.24.5]` or `[v1.22, v1.23, v1.24]`? (Are we really _do_ matrix testing? Please see another problem below.)
> * **Solution:** Consider rephrasing clearly the following above sentence in the README to indicate what we actually run tests for. Eventually we would end up in a new capability matrix design:
> 
> Design 2: Major Versions
> 
> Descheduler	v1.21	v1.22	v1.23	v1.24	v1.25
> v0.25	-	-	X	X	X
> v0.24	-	X	X	X	-
> v0.23	X	X	X	-	-

The [sig-release docs define a Kubernetes versioning](https://github.com/kubernetes/sig-release/blob/d1aab33/release-engineering/versioning.md#kubernetes-release-versioning) as **X.Y.Z** where X is the major version, Y is the minor version, and Z is the patch. We don't guarantee that we will always be testing against the latest patch, since this would require frequent updates to our code and testing infra. We do guarantee that each version will have tests for the latest 
three minor versions, so I think this phrasing is accurate, but a link to the definition of minor version and matrix would be helpful.

> * **Problem 3:** E2E tests only run for single `KUBERNETES_VERSION` in both [helm.yaml](https://github.com/kubernetes-sigs/descheduler/blob/59834cf8a72e4fe55c5e2a325404c934b042cc87/.github/workflows/helm.yaml#L62-L67) and [run-e2e-tests.sh](https://github.com/kubernetes-sigs/descheduler/blob/59834cf8a72e4fe55c5e2a325404c934b042cc87/test/run-e2e-tests.sh#L28).
> * **Solution:** Use [matrix testing](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) in both GitHub Actions and E2E tests to fulfill the aforementioned statement: at least we should run tests against _3 last_ Kubernetes _minor/major?_ versions in matrix manner.

We do effectively have matrix testing with our prow test configs (see https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/descheduler). These set the `KUBERNETES_VERSION` variable to run the e2e's against the past 3 versions, adjusted for each release branch.

The helm test is new this release as a git action, but it was previously tested with prow as well. We should make sure that going forward, we are updating the helm test action to maintain the compatibility matrix. So this is something to work on.

> 1. If we want to support _one major_ Kubernetes version, I think we should _also_ test the all subsequent minor versions. For example, If we want to say _"Descheduler v0.24 support Kubernetes v1.24"_, should better to run a matrix test against `[v1.24, v1.24.1, v1.24.2, v1.24.3, v1.24.4, v1.24.5]`.
> 2. If we want to support _more than one major_ Kubernetes versions, then we should do _matrix in matrix_ test. For example, if we want to support last 2 major Kubernetes releases, shouldn't we do test each minor versions that included in `v1.23`, and then test each minor versions that included in `v1.24`?

See above re:minor/patch versions. I agree if we want to update our policy to support the three latest *patches* of the 3 latest *minor releases*, then that's of course an improvement. The trade off is just the added maintenance

**Comment by Dentrax** [comment]
Thanks for clarification @damemi! And sorry I dropped the ball here. Is there anything we want to update in the README or follow-up issue for this? Otherwise, we can close this one. 😊

**Comment by damemi** [comment]
I think we can close this, it was a good question to bring up so that the semantics can be clarified somewhere. But, it is so detail-specific that it might be too much info for the main docs. In that respect this issue documents the intent good enough imo
