### ISSUE TITLE
Decide on Deschedule/Balance order when running through profiles, and implement the new Descheduler cycle

### ISSUE THREAD

**Issue by knelasevero** [kubernetes-sigs/descheduler#979]
@knelasevero we have two options here:
- go through all the profiles and extension points and invoke them (as done here)
- keep wiring the profiles/plugins in strategy_migration.go and implement invocation of the extension points through framework runAllDeschedule/runAllBalance EPs later.

_Originally posted by @ingvagabund in https://github.com/kubernetes-sigs/descheduler/pull/974#discussion_r991320137_

**Comment by knelasevero** [comment]
Hey all we need to discuss this before we go forward with next steps of the descheduler framework.

Do we think this order really matters? I plan to do some simple scenarios just to check, but would like to know what you think

@a7i @ingvagabund @damemi (please tag anyone that you might think could help deciding this) [anyone, feel free to chime in as this may impact eviction final results]

**Comment by ingvagabund** [comment]
The Deschedule extension point is focused on evicting as many pods as possible without taking into account pod balancing. The Balance extension point is focused on improving even pod spreading. The question is how much is the even spreading actually a benefit. When it comes to bin-packing, one should disable all Balance extension points. So if that's not the intention, keeping pods evenly spread is a good practice. For that, it's preferable to first run all Deschedule eps across all profiles first. And only then the Balance eps across all plugins. Otherwise, there's not much point in running the Balance ep.

**Comment by ingvagabund** [comment]
The profiles were designed to allow configuration of the same plugin multiple times with different parameters. The keyword profile may be unfortunate since it might be seen as an equivalent of a scheduling profile. Where each profile creates a separate pod domain. In the descheduling framework, there's only a single domain since descheduling takes into account a group of pods in general. One group of pods can be evicted be multiple plugins. None of the plugins knowing anything about other plugins.

**Comment by knelasevero** [comment]
We still have time to change the naming of profile, I think. But I can't  think of anything better than that. I understand how it can be confusing, but we can eventually add that explanation in the docs (something like "not to be confused with a scheduling profile approach, profile in our case means something different [...]").

With regards to the [Deschedule / Balance] order, I think it is clear then that balance should come next. No need to show in scenarios [?] (more about why I think showing scenarios where this is beneficial bellow :point_down: ). 

A few comments:

> The Deschedule extension point is focused on evicting as many pods as possible without taking into account pod balancing

But, even though the descheduler doesn't have balacing in mind while evicting with the Deschedule Extension Point, those pods evicted that way will be scheduled in a balanced manner because KS will pick them  up and place somewhere that satisfies the same balancing rules that we monitor. So when we are evicting with the Deschedule EP, we are already balancing **some** pods, even though it is not all of them.

That is why is a bit hard to artificially create scenarios that show the subsequent balance being useful :sweat_smile:, because they are usually huge and complex, and hard to put in a diagram or to describe the sequence of states.

In any case, I think we should go forward with implementing it that way: Dechedule EPs (of all profiles) -> Balance (of all profiles)

**Comment by ingvagabund** [comment]
Done through https://github.com/kubernetes-sigs/descheduler/pull/1177
